name: "Dep job examples"

on: [push]

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello"
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: echo "World"